# kök dizinde (url-shortener/docker-compose.yml)

services:
  api:
    build:
      context: .              # kök – lock dosyasını görebilsin
      dockerfile: api/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  db_data:
